import = ["~/.config/alacritty/gruvbox-material-alacritty.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[selection]
save_to_clipboard = true

[window]
decorations = "Full"
# opacity = 0.8

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 5
y = 6
