import = ["/home/twinj/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
decorations = "Full"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 5
y = 6
