# set -g mouse on
# set -g default-terminal "tmux-256color"
set -sg escape-time 50 # or set to some value larger than 10
set -g focus-events off

set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_status "icon"
set -g @catppuccin_window_current_background "#{@thm_mauve}"

run ~/.config/tmux/plugins/catppuccin/catppuccin.tmux

set -g status-left ""
set -g status-right "#{E:@catppuccin_status_user}"
set -ag status-right "#{E:@catppuccin_status_directory}"

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind r source-file ~/.config/tmux/tmux.conf

set -g base-index 1
setw -g pane-base-index 1
